sudo: false
os: windows

language: node_js
node_js:
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4

matrix:
  allow_failures:
    - node_js: 12

env:
  global:
    - NOV_LTS=8

  matrix:
    - PLTFRM=x64
    - PLTFRM=x86

git:
  depth: false

cache: npm

before_script:
  - NOV=`node -v`
  - npm run pretest
  - cd n-api
  - nvs add $NOV_LTS/x86
  - nvs use $NOV_LTS/x86
  - node -v
  - npm -v
  - npm install
  - npm test
  - node deploy
  - nvs add $NOV_LTS/x64
  - nvs use $NOV_LTS/x64
  - node -v
  - npm -v
  - npm install
  - npm test
  - node deploy
  - cd ..
  - nvs add $NOV/$PLTFRM
  - nvs use $NOV/$PLTFRM

after_success:
  - npm pack
  - 7z a root.zip ".\pem\*" "-xr!*.pem"
