version: 1.0.{build}-{branch}

cache:
  - node_modules -> appveyor.yml

shallow_clone: true

matrix:
  allow_failures:
    - NOV: 14

environment:
  matrix:
    - NOV: 14
    - NOV: 13
    - NOV: 12
    - NOV: 11
    - NOV: 10
    - NOV: 9
    - NOV: 8
    - NOV: 7
    - NOV: 6

  NOV_LTS: 8

platform:
  - x64
  - x86

install:
  # Install NVS.
  - git clone --depth 1 https://github.com/jasongin/nvs %LOCALAPPDATA%\nvs
  - set PATH=%LOCALAPPDATA%\nvs;%PATH%
  - nvs --version
  # Build N-API
  - nvs add %NOV_LTS%/x86
  - nvs use %NOV_LTS%/x86
  - npm install
  - npm run pretest
  - cd n-api
  - npm install
  - npm test
  - node deploy
  - nvs add %NOV_LTS%/x64
  - nvs use %NOV_LTS%/x64
  - npm install
  - npm test
  - node deploy
  - cd ..
  - nvs add %NOV%/%PLATFORM%
  - nvs use %NOV%/%PLATFORM%

build: off

before_test:
  - openssl version
  - node -v
  - npm -v

test_script:
  - npm test

after_test:
  - npm pack
  - 7z a root.zip .\pem\* -xr!*.pem

artifacts:
  - path: root.zip
    name: Root certificates
    type: zip
  - path: .\*.tgz
    name: NPM package(s)
