version: 1.0.{build}-{branch}

# cache:
#   - node_modules

shallow_clone: true

# matrix:
#   allow_failures:
#     - NOV: 11

environment:
  matrix:
    - NOV: 11
    - NOV: 10
    - NOV: 9
    - NOV: 8
    - NOV: 7
    - NOV: 6
    - NOV: 5
    - NOV: 4

  NOV_LTS: 8

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NOV_LTS x64
  - npm install
  - npm run pretest
  - cd n-api
  - npm install
  - node test
  - node deploy
  - ps: Install-Product node $env:NOV_LTS x86
  - npm install
  - node test
  - node deploy
  - cd ..
  - ps: Install-Product node $env:NOV $env:PLATFORM

build: off

before_test:
  - openssl version
  - node -v
  - npm -v

test_script:
  - npm test

after_test:
  - npm pack
  - 7z a root.zip .\pem\* -xr!*.pem

artifacts:
  - path: root.zip
    name: Root certificates
    type: zip
  - path: .\*.tgz
    name: NPM package(s)
